---
- name: Install xDebug
  sudo: yes
  apt: pkg=php-xdebug state=latest

- name: Apply xDebug settings
  sudo: yes
  lineinfile: dest=/etc/php5/fpm/conf.d/20-xdebug.ini
              regexp='^;?{{ item.key }}'
              line='{{ item.key }}={{ item.value }}'
  with_dict: xdebug_settings | default({})
